### ISSUE TITLE
no Default Values in Date Fields (React)

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#1007]
Hi there,

we still have some problems with Date Fields and state Values. (see related issues #440, #643)
I created an example here https://codesandbox.io/s/date-value-and-modal-gcvbvt?file=/src/App.js

Error scenario is this:
1.) in state there is an initial date value (for example, 1.1.2023)
2.) you open a modal dialog with this date field (value is set correctly)
3.) the user changes the date and choose a new value
4.) the user leaves the dialog with cancel, so the state value does not change
5.) if the modal gets reopened the value is still the new selected but not the initial one.

Is there a way to correctly set the value to the initial value?

**Comment by felix-ico** [comment]
Hi @tommy-codez, thanks for reaching out to us. I hope I understand the problem correctly, I think in this case you could assign a reset function to the modal cancel button in order to reset the value of the date picker. I forked your sandbox here to show what I mean https://codesandbox.io/s/date-value-and-modal-forked-kx7y6n

note: I removed the buttons to set the date and instead set the initial value as the default state, and use onScaleChange to update the state from the date picker.

**Comment by felix-ico** [comment]
Hi @tommy-codez just wanted to check up on this again, did my code sandbox help you out? I think the issue here is, rather than scale itself,[ controlled vs uncontrolled inputs](https://reactjs.org/docs/uncontrolled-components.html). There are different ways to get around this, you could probably create a ref as described in the above link as well. 

I would close this issue now, but please feel free to reopen in case these resources do not help you further.
