### ISSUE TITLE
Colors in Scale v3.0.0-beta.100

### ISSUE THREAD

**Issue by robertgebhard** [telekom/scale#1047]
Hi, 

it's very nice to see the Scale design system evolving. I have a question regarding the new color palette. We used the old colors to indicate classic status, so red for error, green for success and yellow for work in progress.

The new color palette now no longer offers a yellow tone. We had used this to indicate the status " In progress". Will there be a yellow tone or more colors again in the future, or do you have any ideas on how we can show the "In Progress" status in our tag?

It would be great if there could be more examples of such use cases. Maybe your design team has already thought about it or has an agenda and could share it with us.

I also tried to update and harmonize all our statuses with the new scale specifications:
![Bildschirmfoto 2022-05-10 um 13 27 13](https://user-images.githubusercontent.com/95682620/167618248-41301bf9-82d8-4525-8d18-ce09ee49edcd.png)

Best regards
Robert

**Comment by JoschaIco** [comment]
Hi Robert,

thanks for your feedback 🙏

First thing to mention: We have now different [colors](https://www.brand-design.telekom.com/scale/?path=/docs/guidelines-colors--page&globals=locale:en;colorMode:light) for text/icons (those you can find in our documentation in the section "Text color function") and for backgrounds (those you can find in the section Background function). It happens  easily that this can be overlooked. I think you used some text-colors also for backgrounds in your example. Maybe we'll have to improve the way these colors are presented.

Second: The logic implemented in you project differs a bit from what we had in mind, when we implementing the functional colors. How are you differentiating between informational and neutral? Would it be possibility to use informational instead of neutral and warning as a separate tag? If you have the feeling that colors, like the orange are too strong for you context, maybe it would be a good solution to use the ones with the subtle backgrounds. Adding a yellow is at least in the short terms not planed (if there is big need for this we'll discuss it of course).

Please let me know if my respond was helpful and also let me know if there is more to clarify.

Best regards
Joscha

**Comment by robertgebhard** [comment]
Hi Joscha,

Thanks for your quick reply.

I definitely noticed the differences in text/icon and background colors. Since a tag is both a kind of icon and a kind of background from my point of view, I tried both color variants. If you could provide more example here of how to use tags that represent a status, that would be awesome.

![Bildschirmfoto 2022-05-11 um 08 12 11](https://user-images.githubusercontent.com/95682620/167780781-d713f486-c35d-4d85-90ed-7f7305b424f8.png)

I think we will reconsider the status mapping in the project and I will see whether with standard background or subtle background. One more question about the contrasts. With Success I only get the contrast of 3.03. The contrast of 4.5 to match AA is not achieved with this. Am I doing something wrong here, because the documentation says AA+ for success.

<img width="1190" alt="Bildschirmfoto 2022-05-11 um 08 11 52" src="https://user-images.githubusercontent.com/95682620/167780843-0496b73c-4674-4a5e-a76d-d4e59e162617.png">
![Bildschirmfoto 2022-05-11 um 08 11 37](https://user-images.githubusercontent.com/95682620/167780866-24cae524-1fb9-400b-be72-9639ac721f65.png)

Best regards
Robert

**Comment by JoschaIco** [comment]
Hi Robert,

indeed, there is mistake in our documentation. Thanks for the hint! The green for success should have black text-color. We will update this soon. Also, we will also work on adding a yellow to our color palette. 

Best regards
Joscha

**Comment by robertgebhard** [comment]
Hi, sorry to bother you again but I noticed another contrast conflict. 

It concerns the contrast of background Functional / Warning / Subtle (--telekom-color-functional-warning-standard
) and font Text & Icon / Functional / Warning (--telekom-color-text-and-icon-functional-warning). 

![Bildschirmfoto 2022-05-12 um 09 04 26](https://user-images.githubusercontent.com/95682620/168012300-96d9d3be-07a1-471b-ba7d-67f65b2a97ae.png)

Unfortunately, I only get a contrast value of 4.41. But the documentation says it is AA+. 

![Bildschirmfoto 2022-05-12 um 09 06 51](https://user-images.githubusercontent.com/95682620/168012388-8483f1a2-f47c-4763-9a0b-d8b9579d054d.png)

Is this perhaps also an mistake in the documentation?

Best regards
Robert

**Comment by JoschaIco** [comment]
Hi Robert,

it's not bothering ;) Your feedback is actually really helpful. Thanks a lot!

This is a mistake. The color should be a shade darker. #b13100 would be the right value. We will update this soon. Also we'll do a more general iteration on our color. So, if there is any further feedback, please let us know. 

Best regards
Joscha

**Comment by acstll** [comment]
[This](https://telekom.github.io/scale/?path=/docs/guidelines-colors--page) is now [fixed](https://colourcontrast.cc/fee2d0/b63d00). 🤓

**Comment by robertgebhard** [comment]
Hi, thanks for your adjustments and the expansion of the color palette.

Unfortunately, I also have problems with the new colors to get the right contrast value.

Since we want to use the colors for the tags, the color contrast must also work for small elements. 

Like you can see there are problems with a contrast of 3,77 for the success tags:
![Bildschirmfoto 2022-07-01 um 07 05 37](https://user-images.githubusercontent.com/95682620/176829300-486c4ac3-d8e2-4c3c-948a-f5cd84276baf.png)
<img width="782" alt="Bildschirmfoto 2022-07-01 um 07 16 39" src="https://user-images.githubusercontent.com/95682620/176829310-fe6ee545-9ee1-43fc-a199-c1f3900e2b6d.png">


And with the error tags the contrast of 3.75 is still too low:
![Bildschirmfoto 2022-07-01 um 07 05 54](https://user-images.githubusercontent.com/95682620/176829319-9b35e1b6-6d72-4b7d-9678-3d685febb07d.png)
<img width="906" alt="Bildschirmfoto 2022-07-01 um 07 12 50" src="https://user-images.githubusercontent.com/95682620/176829322-5a7a1b0d-2bf8-4d41-8b59-1984fa0e0257.png">

I am very sorry but can you clear this up? Should we not use the colors for tags and small tags?

Greetings
Robert

**Comment by acstll** [comment]
Oh, sorry about this. I don't have the answer myself. But we'll look into this during the day and give you an answer as soon as possible 🙏

**Comment by lukasoppermann** [comment]
Hey @robertgebhard I think you are using the wrong colors together.

You should be using the following colors for text: "Text & Icon / On Subtle / Green" (or Red, etc.)

Does this help? I just tested and I get a 4.5:1 contrast

**Comment by JoschaIco** [comment]
Hi Robert,

thanks again for getting on touch. We implemented a whole new category of text&icon-color tokens for this usecase. It is called "On Subtle". These colors are optimized to work with the according subtle tones. The first four are meant to complement the subtle tones of the functional colors. To cover more usecase we decided to also add a token for each subtle tone of the additional colors. These colors should all have a minimum contrast of 4.5. if you find anything further that is not working well from your point of view, don't hesitate to get in touch again.

Best regards
Joscha

<img width="334" alt="image" src="https://user-images.githubusercontent.com/78470963/176840909-07370867-bdf5-4578-a41a-ad8c814a8bc7.png">

**Comment by JoschaIco** [comment]
Lukas was faster :)

**Comment by acstll** [comment]
A matter of seconds ❤️ 

I think the problem is in the documentation, [the new "on sublte" colors are missing in the table, no?](https://telekom.github.io/scale/?path=/docs/guidelines-colors--page&globals=locale:en;colorMode:light)

So the combination @robertgebhard is trying out is [what one assumes from the current table](https://colourcontrast.cc/fad2cf/d91308).

To summarise, the correct (undocumented) combination for Tags would be:

- Text & Icon / On Subtle / Red* (text)
- Functional / Danger* / Subtle (background)

https://colourcontrast.cc/fad2cf/c30a03

(*or any other pair)

Is this correct @lukasoppermann @JoschaIco?

**Comment by JoschaIco** [comment]
Exactly… The "On Subtle"colors are not listed but mentioned in the table. We are planning to redesign the layout of the color table in the documentation. 

<img width="882" alt="image" src="https://user-images.githubusercontent.com/78470963/176845484-d6ce1f81-9004-469d-9bf9-22ef2c68feb4.png">

**Comment by robertgebhard** [comment]
Hi,
thank you for your quick feedback. With the new "On Subtle" colors it works. @acstll is right, because the "On Subtle" colors were not in the documentation I assumed that the "Text color function" colors should be used.

If you could document this, I think it would help others as well. The hint "Color updates: New color category (on-subtle) for texts on colored backgrounds of the gradation Subtle" I didn't notice until now - shame on me. Who can read is clearly in the advantage.

Greetings
Robert
