### ISSUE TITLE
New Component: Tags input

### ISSUE THREAD

**Issue by jano314159** [telekom/scale#1058]
Hi all :)

I would like to ask a new UI compontent tags input

**Describe the feature request**
Input element for defining one or more tags.

**Describe the use case**
We would like an input element where the user can add one or more tags into the input field.

**Additional context**
Something similar to this example below
![tags_input](https://user-images.githubusercontent.com/86777428/168578640-39c34728-d4dd-4469-b98c-1a23986c5b47.gif)

Thank you

**Comment by filipjnc** [comment]
You can kind of achieve the same behavior by combining `ScaleTextField` and `ScaleTag`:
https://codesandbox.io/s/brave-hypatia-0x76zt?file=/src/App.js

I think what an actual tags input component should look like is this:
https://codesandbox.io/s/grihzn?file=/demo.tsx

Prerequisite for that is a Multiselect (Autocomplete) Component.

**Comment by acstll** [comment]
> You can kind of achieve the same behavior by combining `ScaleTextField` and `ScaleTag`: https://codesandbox.io/s/brave-hypatia-0x76zt?file=/src/App.js

I completely agree with @filipjnc — this pattern can be implemented already, only the autocomplete feature (or an autocomplete component) could be used to improve it

> I think what an actual tags input component should look like is this: https://codesandbox.io/s/grihzn?file=/demo.tsx

this is brilliant, thanks a lot for sharing. I wonder, in your opinion, what would it take to make this look like Scale? An autocomplete component you could customise in order to remove the border? or maybe a more lower level thing like a static `listbox`?

Did you know there are design tokens available in JS? https://unpkg.com/@telekom/design-tokens@1.0.0-beta.1/dist/telekom/js/telekom-design-tokens.light.js
 
> Prerequisite for that is an Autocomplete component. I'd close this ticket in favour of #439

@jano314159 if you agree, I would follow this suggestion.

**Comment by filipjnc** [comment]
> 
> > I think what an actual tags input component should look like is this: https://codesandbox.io/s/grihzn?file=/demo.tsx
> 
> this is brilliant, thanks a lot for sharing. I wonder, in your opinion, what would it take to make this look like Scale? An autocomplete component you could customise in order to remove the border? or maybe a more lower level thing like a static `listbox`?

I think we need an `Autocomplete`/`Combobox` component first, which combines styles and behaviors from `TextField `and `DropdownSelect`. 
Then, based on that we need a `ComboboxMultiselect` component which includes a list of `Tag` components `inline-flex`ed with the `<input>` element. Also, it should replace the `IconCollapse` icons with an actual button that toggles the listbox visibility. 

I put something together in React + Downshift with Telekom styling. It's by far not polished, but it depicts the expected behavior:
https://stackblitz.com/edit/telekom-scale-combobox-multiselect?file=src%2FApp.tsx&terminal=dev

**Comment by acstll** [comment]
That's super clear now @filipjnc — thanks again for taking the time.

I would only like to point out that in terms or `role`s, the `combobox -> textfield + listbox` in the graph might not be accurate. Since the input itself (TextField in this case) would get [the `combobox` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Combobox_Role), which in turn controls the `listbox`. However, from a usage perspective, it makes perfect sense.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/851105/185967589-142b5154-51e7-43cb-80db-0b095377db59.png">

We will focus on this below when the time is right 🙏

> we need an Autocomplete/Combobox component first, which combines styles and behaviors from TextField and DropdownSelect.
