### ISSUE TITLE
scale-tooltip failed cypress Test

### ISSUE THREAD

**Issue by GemSer** [telekom/scale#1063]
**Scale Version**
3.0.0-beta.103

**Framework and version**
Angular Version: 12.0.3
Cypress Version: 9.5.4 

**Current Behavior**
When testing ui in Cypress, an error occured when an element is wrapped inside a scale-tooltip:
![grafik](https://user-images.githubusercontent.com/23645040/169009167-b849c2ee-9ada-4aa3-a175-ab3a89a5b84e.png)

It works if we comment out the following line (1746) in the "show()" function in the file scale-tooltip.entry.js:
![grafik](https://user-images.githubusercontent.com/23645040/169008572-9811692b-850a-4860-b2dc-192b1eb8c7e0.png)

**Expected Behavior**
No errors, Cypress runs successful

**Comment by felix-ico** [comment]
Hi @GemSer thanks for opening this issue. This seems to be caused by one of the libraries we use, popperjs. We have been already thinking/testing how to replace popperjs with another library for positioning elements such as the tooltip, this issue would be another reason in favor of doing that. Will definitely bring this up in the team

**Comment by nowseemee** [comment]
Hey all, thanks for the valuable discussion. A rewrite of the tooltip component utilizing `floating-ui` instead of `popperjs` has been published (3.0.0-beta.108) and hopefully solves this issue. Feel free to reopen in case something is still not right.
