### ISSUE TITLE
Date picker-space under the footer

### ISSUE THREAD

**Issue by BarboraUngerova** [telekom/scale#1087]
**Scale Version**
3.0.0-beta.55

**Framework and version**
react-version 17, we are using auto-generated scale wrapper packages

**Current Behavior**
When we are using date picker in our page, there is white space under the footer.

**Expected Behavior**
White space not to be there.

**Code Reproduction**
https://codesandbox.io/s/peaceful-franklin-zcf0yr?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chome

**Comment by marvinLaubenstein** [comment]
Good morning @BarboraUngerova, thank you for pointing out the problem. I will have a look at it.

**Comment by BarboraUngerova** [comment]
It is happening when datepicker is right above the footer like in screenshot.
![Screenshot from 2022-06-02 09-40-54](https://user-images.githubusercontent.com/84072142/171580055-a7f8434e-ef30-4fcd-ad9d-d4874f8ddb01.png)

**Comment by felix-ico** [comment]
Hi @BarboraUngerova, @marvinLaubenstein, I had a look at this and it seems related to the [duet-date-picker](https://duetds.github.io/date-picker/) which scale uses internally. The date-picker is always rendered but set to `visibility: hidden` when not active, causing it to take up that space. I will bring this up with the team to see what workaround we can provide for this.

**Comment by felix-ico** [comment]
Hi @BarboraUngerova just brought this up with the team. The simplest solution would be, when using a scale-date-picker, to consider the necessary space for the date-picker to be opened and account for it (basically avoid placing the date-picker right above the footer). I hope that is a compromise that works for you since refactoring this component to allow the effect you requested would require a quite large effort for a small return on this edge case.
