### ISSUE TITLE
scale-text-field applies styles globaly

### ISSUE THREAD

**Issue by TFlaxx** [telekom/scale#1102]
**Scale Version**
@telekom/scale-components: 3.0.0-beta.106

**Framework and version**
@nuxt/webpack-builder: 3.0.0-rc.4
nuxt (vue3): 3.0.0-rc.4

**Current Behavior**
scale-text-fields property `styles` does add the styles globaly
(example with `div {background-color: red;}` )
![image](https://user-images.githubusercontent.com/6446164/174304032-179368d7-bc1b-484b-86be-2ec5923c0586.png)

**Expected Behavior**
Property `styles` should only add the styles to the child elements like this:
![image](https://user-images.githubusercontent.com/6446164/174304225-d65045a9-c476-4e0f-82a7-d7308263dcbb.png)

**Code Reproduction**
[Reproduction](https://codesandbox.io/s/scale-components-vue3-forked-r7bi61?file=/src/App.vue)

**Desktop Browser**
Chrome, Firefox

**Additional context**
There was already another issue with similar context #1046 .
The scale-button does have a `#shadow-root` inside, while its missing inside scale-test-field. Maybe this is the problem?
![image](https://user-images.githubusercontent.com/6446164/174306522-8cb40417-1f77-4414-adf4-f5c20f32b6d7.png)
![image](https://user-images.githubusercontent.com/6446164/174306584-65b733e8-50b8-4b22-9bda-43d86ecf82e3.png)

**Comment by nowseemee** [comment]
Hi @TFlaxx, thanks for writing to us. Yes, you are right, the components which are implementing form inputs are not having shadow DOM due to technical constraints around form submission. This is a known limitation so we would need to suggest scoping your custom styles to the element in an old-school way, perhaps by adding a specific class name. Feel free to reopen in case you have doubts.
