### ISSUE TITLE
Modal: issues with closeButton and slots

### ISSUE THREAD

**Issue by Pinkcamouflage** [telekom/scale#1168]
**Scale Version**
v3.0.0-beta.110

**Framework and version**
vite: 3.0.1
vue: 3.2.37

**Code Reproduction**
Try: [Telekom Scale Storybook](https://telekom.github.io/scale/?path=/story/components-modal--standard&args=actions.p:dhfkasjdhfkasdh&globals=locale:en;colorMode:light)

**Additional context**
We cannot use "document.getElementById()" because we have a virtual DOM.
How can you then change the function that is being executed on the closeButton and the background of the modal?

Additionally, can you show me an example of how to use slots within the modal? Adding a slot property to element tags does not work.

**Comment by acstll** [comment]
Hey @Pinkcamouflage, thanks for getting in touch.

What element in particular are you trying to get with `getElementById`? If you're trying to query `<scale-modal>` itself, it shouldn't matter if there's a virtual DOM or not, there should be a way in the library/framework to access the DOM ([with `ref` s in this case](https://vuejs.org/guide/essentials/template-refs.html), if you're using Vue).

## Regarding the close button

In order to modify the behaviour, you can listen to the `scale-before-close` event on `<scale-modal>`. The event detail will carry a `trigger` prop with a string value, with possible values being the following, depending on the action that triggered th event:

- `CLOSE_BUTTON`: the close button was click
- `ESCAPE_KEY`: the Escape key was pressed
- `BACKDROP`: the backdrop or overlay (what you call background?) was clicked

If you call `event.preventDefault()`, the modal won't close. That way you can control upon which action is the modal closing.

```js
const modal = document.querySelector('scale-modal')
// Disable closing the modal by clicking the overlay
modal.addEventListener('scale-before-close', (event) => {
  if (event.detail.trigger === 'BACKDROP') {
    event.preventDefault()
  }
})
```

We're aware this feature is not properly documented! :pray:

## Regarding slots

There are 2 named slots besides, the default slot: `action`, which you can use for buttons, and `close-icon` which you can use to replace the icon in the close button (only the icon, not the button itself).

You can place many buttons next to each other, as long as they have the `slot="action"` attribute, they will render in the right place.

```html
<scale-modal>
  <!-- your content -->
  <p>Hello World</p>

  <!-- the buttons -->
  <button slot="action">Cancel</button>
  <button slot="action">OK</button>
</scale-modal>
```

I'm noticing now that the snippets in Storybook are missing the `slot="action"` part in most cases, that's our bad!

---

I will prepare a working example in codesandbox in a bit.

**Comment by Pinkcamouflage** [comment]
Hey @acstll,
thank you for your quick answer. I tested both versions of your proposed fix. This 
```
const modal = document.querySelector('scale-modal')
// Disable closing the modal by clicking the overlay
modal.addEventListener('scale-before-close', (event) => {
  if (event.detail.trigger === 'BACKDROP') {
    event.preventDefault()
  }
})
```
does not work for us. But the solution with adding the eventlistener via `@scale-before-close`, as you did in the codesandbox, works perfectly for us. Thank you!

**Comment by acstll** [comment]
The snippet was meant to illustrate the idea only, sorry 🙏 — I'm glad it worked 🙂
