### ISSUE TITLE
Tooltip trigger area overlaps each other and don't display properly

### ISSUE THREAD

**Issue by goatfryed-holos** [telekom/scale#1445]
**Scale Version**
beta3.0.0-117

**Framework and version**
vue3 with standard web components, issue is framework independent.

**Current Behavior**
The scale tooltip area is hidden via aria-hidden and opacitiy 0. It is not actually hidden as an element. This causes the tooltip to appear as soon as the mouse hovers any of the area where the tooltip would appear.
If this overlaps with another tooltip area, the user can not effectivly hover that tooltip. Also it's confusing, because the user might intentionally navigate the mouse around the tooltip holding element and it still appears.

**Expected Behavior**
The tooltip should only display on hover of the holding element and stay displayed while focus is within.

**Code Reproduction**
[TODO, currently issues forking code sandbox]
[Scale and Plain HTML](https://codesandbox.io/s/scale-components-plain-html-template-qfi9mp)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome 104

**Additional context**
since it's not possible to add additional selectors to part selectors (e.g. part & aria-hidden), i couldn't find a fitting workaround yet

**Comment by felix-ico** [comment]
Hi @goatfryed-holos thanks for reporting the issue. I am not 100% sure that I understood the problem correctly, but I think what you are trying to do is to have nested elements each with its individual tooltip, and make it so that the parent tooltip is hidden when a child tooltip is showing. I set up a codesandbox here https://codesandbox.io/s/scale-components-plain-html-template-forked-9yceqe?file=/index.html to show how to achieve this effect by calling the event listener and checking the event target.

Please let me know if this helps you or if your issue is a different one.

**Comment by goatfryed-holos** [comment]
Sorry for ghosting you on this one. Totally missed your question and forgot about this one.

For reference, I've created an initial code sandbox that shows what I tried to do back then, but can't reproduce the issue in the current or old version yet.
https://codesandbox.io/p/sandbox/scale-components-plain-html-template-forked-zmyxr5

I close this issue for now and will reopen it, if I encounter it again.
