### ISSUE TITLE
styling the flex-direction of a radio-group

### ISSUE THREAD

**Issue by Tobssen** [telekom/scale#1838]
I am struggling to arrange the radio buttons inside a radio-group horizontally.
When I go to the developer tools of Chrome and find the corresponding shadow-root of the radio group, I can edit the div with the class "radio-button-group__container" to use flex-direction: row; instead of flex-direction: column; (This works). How do I do this from the style sheet of the page which uses the component? I have tried multiple CSS statements non of which worked. Is this possible or somehow supported out of the box?

**Comment by ayeshaa-m** [comment]
@Tobssen 
For customising elements inside the shadow DOM we recommend using ::part() (as stated in https://telekom.github.io/scale/?path=/docs/guidelines-customization-and-themes--page), but for non-shadow DOM components it's not so clearly documented… users can just target the CSS classes.

In the upcoming release part attribute is provided for radio-button-group__container div. So that you can change the flex-direction. Hope this helps.

**Comment by Tobssen** [comment]
Thanks @ayeshaa-m for the fast reaction and providing the update!
So I would then be able to use a CSS like below to get the flex-direction changed for the radio group?
`
scale-radio-button-group::part(base) {
  flex-direction: row;
}
`

When is the next release coming?

**Comment by ayeshaa-m** [comment]
@Tobssen Yes, You can use the code you have mentioned in above comment. Can not comment on timing of next release but the fix will be present in version v3.0.0-beta.135
Hope this helps :) 
- Thanks
