### ISSUE TITLE
"@telekom/scale-components-react" is outdated and does not support new scale components

### ISSUE THREAD

**Issue by tischrei** [telekom/scale#1960]
**Scale Version**
    "@telekom/scale-components": "^3.0.0-beta.134",
    "@telekom/scale-components-react": "^3.0.0-beta.56"

**Framework and version**
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "next": "^13.4.4",

**Current Behavior**
The newly created scale components cannot be used as intended. Elements like scale chip are not supported. The wrapper is outdated. It would be nice if the wrapper would be updated in the same pipeline as the components are updated.
For instance ScaleChip is not supported.

**Expected Behavior**
All scale components should be supported.

**Comment by felix-ico** [comment]
Hi @tischrei, every time a new scale-components version is released the scale-components-react version gets bumped as well. Could you please try to set both dependencies to the same version (beta.134) and see if that solves your issue?

**Comment by SebastianGode** [comment]
Hey @felix-ico 
I think the underlying issue is an wrong documentation. The [documentation ](https://telekom.github.io/scale/?path=/docs/setup-info-scale-and-react--page )states to install:
```
@telekom/scale-components@next
```
and for the wrapper package
```
@telekom/scale-components-react
```

This will result in having an outdated wrapper but an up-to-date component package installed. And that will result in the error mentioned above. So please have a look at the documentation and update it. Also please remove the other examples for the wrapper packages as e.g. `reactify-wc` isn't compatible with current react versions anymore.
