### ISSUE TITLE
Console error(Header component): Cannot read properties of undefined (reading 'setAttribute')

### ISSUE THREAD

**Issue by Dondo24** [telekom/scale#2099]
Scale Version
3.0.0-beta.134
Framework and version
Angular16

**Current Behavior**
![console error](https://github.com/telekom/scale/assets/22313013/bbf169f6-20b8-4605-b869-767af8861b6c)

**Expected Behavior**
Header component can find only 'a' and 'button' html elements.If i use something else for example scale button i get this error.
![Screenshot 2023-08-14 193000](https://github.com/telekom/scale/assets/22313013/818fda72-f311-40c8-a62c-aed0c8d6def3)

**Comment by felix-ico** [comment]
Hi @Dondo24, I'm not really sure that this is a bug or expected behaviour. I think, from a UX/UI perspective, that the header should only accept links or "icon buttons", but it is not expected to place another type of button (like a scale-button) in the header. 

Please feel free to reopen the issue if you need to use a scale-button in the header, but then i would rather see it as a feature request than a bug..
