### ISSUE TITLE
Bug in Flyout Menu - bad positioning of scale-menu-flyout-list dropdown

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#2122]
**Scale Version**
[v3.0.0-beta.139](https://github.com/telekom/scale/releases/tag/v3.0.0-beta.139)

**Framework and version**
any

**Current Behavior**
Open in Firefox: https://telekom.github.io/scale/?path=/docs/components-flyout-menu--standard&globals=locale:en;colorMode:light

https://github.com/telekom/scale/assets/49948501/a6895ac8-7999-4187-8b4c-7e35d64bd303

This bug also happens in Chrome if Flyout Menu is included in header.
There are other issues created about this issue happening if Flyout Menu is part of the modal window.

**Expected Behavior**
Dropdown should be opened next to Flyout Menu trigger button.

**Comment by felix-ico** [comment]
Hi @mato-a can you confirm that this issue happens when using the component outside of storybook? It looks to me like it is in fact broken, but only on firefox in the "docs" view of storybook (probably due to the iframe container that wraps the element). When opening the canvas view it seems to work correctly in firefox (https://telekom.github.io/scale/iframe.html?id=components-flyout-menu--standard&globals=locale:en;colorMode:light&args=&viewMode=story). 

> This bug also happens in Chrome if Flyout Menu is included in header.

Regarding this, I am not sure that the flyout menu is supposed to be used in the header. I guess that, if needed, this would require some additional changes to the flyout component or the header component.

>There are other issues created about this issue happening if Flyout Menu is part of the modal window.

I saw one issue that seems to only trigger when setting a css transform on the window part of the modal, which in turn seems to be a workaround for a datepicker within a modal https://github.com/telekom/scale/issues/2035. I'll bring this up in the team as I am not sure what component actually needs to receive the bugfix in this case.

**Comment by mato-a** [comment]
Hi @felix-ico,

I can confirm that this issue is happening in header if I try to use Flyout Menu in Header in `lang-switcher` slot. I have solved it by moving this dropdown into `functions` slot.



>>    This bug also happens in Chrome if Flyout Menu is included in header.

> Regarding this, I am not sure that the flyout menu is supposed to be used in the header. I guess that, if needed, this would require some additional changes to the flyout component or the header component.


I think it would be useful to support using dropdown menu in various parts of the header - e.g. dropdown is useful if you have more languages to choose from also in `lang-switcher` slot.

**Comment by mato-a** [comment]
Hi @felix-ico,

Actually I found the cause. So when I use something like this `class="translate-y-1/4"` to move the Flyout menu little bit up or down then dropdown is opened incorrectly in the right top corner of the screen instead of under the button. This happens both in `lang-switcher` and` functions` slot.

```html
          <scale-telekom-nav-item class="translate-y-1/4">
            <app-theme />
          </scale-telekom-nav-item>
```

**Comment by felix-ico** [comment]
Hey @mato-a, I am testing this out. I think there are some issues with placing the flyout-menu in the header for something like a language switcher (for example, i think it would not work correctly in the mobile view in this case). 

Anyway, I tried to set it up here https://codesandbox.io/s/scale-components-plain-html-template-forked-q6q5ss?file=/index.html (windowed view: https://q6q5ss.sse.codesandbox.io/) and actually I don't see any issue on Desktop Chrome/Firefox. Could you confirm?

**Comment by mato-a** [comment]
Hi @felix-ico,

Yes I can confirm. Thanks for your help. I'll close the issue.

As I mentioned above the issue actually happens only if I use something like:

```html
  <scale-telekom-nav-item class="translate-y-1/4">
        <app-theme />
      </scale-telekom-nav-item>
```

But I think it is not really a bug. Position of the Flyout menu can be changed by overriding css variables instead which works fine.
