### ISSUE TITLE
Telekom Brand Header & Navigation Documentation

### ISSUE THREAD

**Issue by vissarionas** [telekom/scale#2198]
**Scale Version**
3.0.0-beta.143

**Framework and version**
ReactJS

**Documentation Request**
Telekom Brand Header & Navigation

Missing information about the icon navigation part, the responsive design, and how this header can be used together the with app shell and footer.

**Comment by felix-ico** [comment]
Hi @vissarionas, sorry for the delay, we kept the storybook documentation rather minimal to avoid huge chunks of (repeating) html.  We do have some examples on how to use the different types of header here https://github.com/telekom/scale/blob/main/examples/telekom-header-samples/ - these are in plain html, but there shouldn't be any differences in react (other than using the wrapped react components instead of the web components directly).

**Comment by amir-ba** [comment]
@vissarionas I will close this, due to inactivity. You can create another issue when your question still exists.
