### ISSUE TITLE
Wrong master checkbox work in the scale-checkbox-group

### ISSUE THREAD

**Issue by Tireile** [telekom/scale#2221]
**Scale Version**
3.0.0-beta.134

**Framework and version**
Vue version 3.2.33

**Description**
We are using **scale-checkbox-group** component. And master checkbox of this component doesn't react on changing options quantity.
For example we have checked state of master checkbox and its children. After changing options quantity(e.g. adding new one) then state of the master checkbox should be changed on the **indeterminate** because new option(child) has state unchecked. But master checkbox state remains **checked**.

Also there is another bug with state of master checkbox. When **disabled** prop changing on **true** then disabled state of children work as well but master checkbox remains **active**.

**Code Reproduction**
For reproducing these bugs I've created [sandbox](https://codesandbox.io/p/sandbox/bold-ride-4b3k5b?file=%2Fsrc%2FApp.vue%3A77%2C10)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: GoogleChrome
 - Version 119.0.6045.160 (Official Build) (64-bit)

**Demonstration**

**bug**:
![bug](https://github.com/telekom/scale/assets/35307181/ac441539-3580-4f36-87ad-2d9c19de5d8d)

**expected behaviour**
![demo1](https://github.com/telekom/scale/assets/35307181/72329ae5-17a5-4699-b217-5f8a293794f3)

**Comment by felix-ico** [comment]
hi @Tireile, I just had a look at these issues:

Regarding the first problem, this seems to be already fixed in the latest version of scale:, i forked your sandbox using scale-components beta.143 here: https://codesandbox.io/p/sandbox/sparkling-haze-lqz32h?file=%2Fpackage.json%3A11%2C49

About the disabled state, the issue here is that `scale-checkbox-group` does not have a disabled prop, only the child `scale-checkbox` items can be set to disabled. So, in the current implementation, if you want the whole group to be disabled you would have to set disabled on each `scale-checkbox`.
