### ISSUE TITLE
ScaleSidebarNavItem current prop issue(React)

### ISSUE THREAD

**Issue by BarboraUngerova** [telekom/scale#335]
current prop(found it in storybook about ScaleSidebarNav) is misbehaving.
Even if we set it to false, it still highlights the ScaleSidebarNavItem with magenta vertical line on the left.
![Screenshot from 2021-05-12 10-59-08](https://user-images.githubusercontent.com/84072142/117951097-1ea85c00-b314-11eb-9463-1c90da952520.png)

example of code: 

```
  <ScaleSidebarNav>
    <ScaleSidebarNavItem current={false}>
      <Link to="/admin/organizations">Organizations</Link>
    </ScaleSidebarNavItem>
    <ScaleSidebarNavItem current={true}>
      <Link to="/admin/users">Users</Link>
    </ScaleSidebarNavItem>
    <ScaleSidebarNavItem>
      <Link to="/admin/businessunits">Business Units</Link>
    </ScaleSidebarNavItem>
    <ScaleSidebarNavItem>
      <Link to="/admin/projects">Projects</Link>
    </ScaleSidebarNavItem>
    <ScaleSidebarNavItem>
      <Link to="/admin/marketplaces">Marketplace</Link>
    </ScaleSidebarNavItem>
  </ScaleSidebarNav>
```

**Comment by nowseemee** [comment]
Hi Barbora, 

The current prop's expected type is `string` or `null`. 

From the readme:

| Property       | Attribute       | Description                                                                                                             | Type      | Default     |
| -------------- | --------------- | ----------------------------------------------------------------------------------------------------------------------- | --------- | ----------- |
| `active`       | `active`        | Text gets the active color                                                                                              | `boolean` | `false`     |
| `bold`         | `bold`          | Bold text                                                                                                               | `boolean` | `false`     |
| `condensed`    | `condensed`     | Used normally for third level items, remove the bottom border                                                           | `boolean` | `false`     |
| `current`      | `current`       | Mark the child link as "current" with `aria-current=page`. Provide the text hint if needed, default is: "Zurzeit aktiv" | `string`  | `null`      |
| `nestingLevel` | `nesting-level` | Nesting level within the <scale-sidebar-nav> parent, gets set automatically                                             | `number`  | `undefined` |
| `styles`       | `styles`        | (optional) Extra styles                                                                                                 | `string`  | `undefined` |

https://github.com/telekom/scale/tree/main/packages/components/src/components/sidebar-nav-item


And you are right, it should handle `false` since that is allowed by the ARIA specs: https://www.w3.org/TR/wai-aria-1.1/#aria-current

... so I'll leave this ticket open until we extend the allowed types but for the time being you could pass `''` or `null` instead of `false` for a quick fix. I'll come back to you once a patch is released. 

Thanks for reporting this issue.

**Comment by nowseemee** [comment]
With the latest release (`3.0.0-beta.9`) it should handle boolean values well 🤞🏻
