### ISSUE TITLE
Multiple style issues for React App in latest version. 

### ISSUE THREAD

**Issue by gaurishkamat** [telekom/scale#385]
Margins for input elements are missing, ScaleLink component doesn't look the same. ScaleAppShell's prop portalName shown with a list-style-type disc.
[https://imgur.com/a/Vg22Lzd](url)

**Comment by christopherGdynia** [comment]
Which version do you use?

**Comment by christopherGdynia** [comment]
The list-style-type was fixed with issue #366 and beta version 3.0.0-beta.12. In #383 you can see an example for styling the portalname differently.

**Comment by acstll** [comment]
- The margins on the inputs are intentionally missing. This way people is free to handle spacing according to the specific needs of each context. We can definitely discuss adding them back in a flexible way.
- `ScaleLink` has a new color and it might have slightly changed since version 1, what are you comparing it to?
- As @christopherGdynia pointed out (thank you!), the `portalName` bullet point bug was recently fixed in `3.0.0-beta.12`

**Comment by gaurishkamat** [comment]
Hi @christopherGdynia  and @acstll thanks that resolved my issues. Forgot to mention I was using the version `3.0.0-beta.7`.
