### ISSUE TITLE
Difference between Scale Icon and Scale IconLib

### ISSUE THREAD

**Issue by Lalaluka** [telekom/scale#405]
Hi,
I just noticed a difference between the `<scale-icon>` Element and the Scale Icon library.
Scale-icon uses the `fill` Attribute to color an icon while the Library has the `color` Attribute.

Code Examples:
```
<scale-icon-alert-security color="green"></scale-icon-alert-security>
<scale-icon fill="green" path="M12...75h8.7z"></scale-icon>
```

Is there a specific functional reason for the difference between `fill` and `color`?

If yes it might be helpful to state it in the Storybook somewhere. Or at least make the Icon Library Tab interactive (at the moment it's static).

If not I think it would be nice to have one Attribute name for the functionality e.g. add color to `scale-icon` or fill to the IconLibrary.

**Comment by Lalaluka** [comment]
I think it's not worth opening another Ticket for it but for the icon _device-device-tv_ the **selected** svg from B&D has been uploaded instead of the default one.
Default:
<img width="65" alt="Bildschirmfoto 2021-06-15 um 12 50 06" src="https://user-images.githubusercontent.com/26364692/122040543-37ef6d00-cdd8-11eb-843e-9ae24cc2db4f.png">

Scale: 
<img width="65" alt="Bildschirmfoto 2021-06-15 um 12 51 07" src="https://user-images.githubusercontent.com/26364692/122040657-5bb2b300-cdd8-11eb-81c9-907f4e0d9c08.png">

I can't fix it with a quick PR, because I think the icon Download from Brand&Design is bugged?
[B&D Download](https://www.brand-design.telekom.com/asset/icon-for-user-interfaces-0-icons-fr-user-interfaces/)
I can't retrieve the full IconLibrary just partial Icons 🤔
Maybe someone else has access to a full zip :)

**Comment by acstll** [comment]
hey @Lalaluka thanks for this!

> Is there a specific functional reason for the difference between fill and color?

the reason is that they do kinda different things, `scale-icon` is mostly a wrapper, you can use any `path` with it so being able to set `fill` or `stroke` independently made sense. This isn't true the Telekom's icon library, you don't need such granularity, so `color` seemed enough.

I can understand it's not consistent and that's not nice.

Renaming an attribute would be a breaking change though, and we would like to avoid that at the moment.

Do you think adding an `fill` attribute to the icon library as an alias to `color` would help? In my opinion things are good as they are. But feel free to open a PR (as always 🙂), if you think you can make it better without introducing any breaking changes.

---

Regarding the `selected` states. They are missing for 2 icons currently:

- `device-device-tv`
- `content-media-folder`

As you were guessing, this is a bug in the source. So we have to ask… Thanks for bringing it up.

**Comment by Lalaluka** [comment]
Yeah, I agree that renaming something is not nice. The reasoning for the difference is understandable. I didn't think that far.
I had the same Idea of introducing `fill` to the icon Library. I will take a look if the functionality is technically similar enough to justify adding it.

About the Icons:
Ok, so we just have to wait :)

For that chance that I'm planning on changing something with `fill` I will leave this Issue open for now. If I decide not to add anything I will close it

**Comment by acstll** [comment]
#412
