### ISSUE TITLE
Example with Angular 7 is no longer supported

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#419]
Example using Angular uses unsupported version of Angular - version 7: https://github.com/telekom/scale/tree/main/examples/boilerplate-angular
I recommend to update it to version 12.
Currently supported Angular versions: https://angular.io/guide/releases#support-policy-and-schedule

Also I was not able to find in the documentation if all Angular versions are supported by Scale: 
https://www.brand-design.telekom.com/scale/?path=/story/scale-for-developers-scale-and-angular--page
Please update the documentation with explicitly supported versions.

**Comment by acstll** [comment]
Hello @mato-a, thanks for opening this and for your recommendation.

We've been working on new examples with Angular 12, currently in a private repo. We will make them public (hopefully) next week. The new boilerplate will include some custom Custom Value Accessors to use with reactive forms.

Regarding support, if you're using the `@telekom/scale-components-angular` package, you're limited to Angular 7. We're gonna deprecate this package very soon. One of the main reasons being support across different Angular versions…

If you use only the core package `@telekom/scale-components`, then you can use any of the latest versions of Angular. Since Scale components are just Web Components.

We will be updating the docs together when the new examples are made public.

---

I'm pasting here the yet unreleased latest version of our docs regarding Angular:

## Setup

First, install the package:

```bash
npm install @telekom/scale-components
```

Load the component library in `main.ts`:

```ts
// src/main.ts
import { defineCustomElements } from '@telekom/scale-components/loader';

// ...

defineCustomElements();
```

Then, load the CSS in the `angular.json` config file:

```json
// angular.json
{
  "build": {
    "styles": [
      "node_modules/@telekom/scale-components/dist/scale-components/scale-components.css"
    ]
  }
}
```

In order for Angular to be able to handle Non-Angular element names, include the [`CUSTOM_ELEMENTS_SCHEMA`](https://angular.io/api/core/CUSTOM_ELEMENTS_SCHEMA) in `src/app/app.module.ts`:

```ts
// src/app/app.module.ts
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@NgModule({
  // ...
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppModule {}
```

If using routing, also in `src/app/app-routing.module.ts`:

```ts
// src/app/app-routing.module.ts
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@NgModule({
  // ..
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppRoutingModule {}
```

You should now be able to use Scale components in your templates:

```html
<div>
  <scale-button>Click!</scale-button>
</div>
```

## Events in Angular

In order to prevent collisions with standard events and compatibility with other libraries and frameworks, the custom events emitted by some Scale components are prefixed with `scale`. Event names are camelCased (e.g. `scaleChange`). You can find documentation for these custom events on the respective component pages in the docs section.

You can bind to `scale`-prefixed events with the regular Angular syntax:

```html
<scale-slider (scaleInput)="setValue($event)"></scale-slider>
```

**Comment by mato-a** [comment]
Thanks for a quick response :smile:
