### ISSUE TITLE
ScaleDropdown default value (React)

### ISSUE THREAD

**Issue by vissarion-tsitoglou-pn** [telekom/scale#534]
I cannot find a proper way to render a ScaleDropdown component with an empty (default) value. It is rendered with the last `option` provided.

The workaround is having that extra option `<option disabled selected>{undefined}</option>`, which does not seem the best way to achieve that.

Any ideas?

**Comment by acstll** [comment]
Thanks for opening this.

Adding an empty `<option>` is the right way to do it, because that's how the `<select />` element works. Without an empty `<option>` the first one is selected by default.

```html
<select>
  <option></option>
  <option value="a">A</option>
  <option value="b">B</option>
  <option value="c">C</option>
</select>
```

This is what I would suggest for an empty default value:

```js
<ScaleDropdown label="Options" value={''}>
  <option />
  <option value={'a'}>A</option>
  <option value={'b'}>B</option>
  <option value={'c'}>C</option>
</ScaleDropdown>
```

In React you set `value` instead of using the native `selected` attribute. You probably know this already, but just in case I would recommend checking out [the React docs regarding form elements](https://reactjs.org/docs/forms.html#the-select-tag).

And here's a more complete example using the ScaleDropdown's `controlled` attribute to enable "controlled" React behaviour:

```jsx
import React, { useState } from 'react'
import { ScaleDropdown } from '@telekom/scale-components-react-neutral';

function Example() {
  const [option, setOption] = useState('')
  const handleChange = (event) => setOption(event.detail.value)

  return (
    <>
      <ScaleDropdown label="Options" value={option} onScaleChange={handleChange} controlled>
        <option />
        <option value={'a'}>A</option>
        <option value={'b'}>B</option>
        <option value={'c'}>C</option>
      </ScaleDropdown>
    </>
  );
}
```

I hope this helps!

**Comment by vissarion-tsitoglou-pn** [comment]
Thanks for the quick reply!

The error about default value is gone after setting `controlled` prop to true, and fixing my mistake about `event.detail.value`. I failed to spot this detail, and used `event.target.value`.

Thanks again!
