### ISSUE TITLE
[ReactJS] + beta 19 - Checkbox checked state not working anymore

### ISSUE THREAD

**Issue by BB-19** [telekom/scale#563]
It seems like the beta 19 changes broke the checkboxes (maybe more ?) for React-JS .

When using the checkbox component, setting a boolean for the checked state results as a string in the html (checked="true" or checked="false"). This worked in the previous version without issues.
Same applies for the disabled state. A workaround would be the useRef + useEffect hook to set the state manually.

### See: 
https://codesandbox.io/s/serene-gwen-bj22c?file=/src/App.js

**Comment by nowseemee** [comment]
Thanks for letting us know, will look into this ASAP.

**Comment by BB-19** [comment]
P.s.: Providing undefined instead of false is also a possible workaround for now.

**Comment by oddcelot** [comment]
It seems that the refactor of the checkbox in the styling department uncovered something that is not working between stencil and react.
This seems to work as expected in Vue and vanilla implementations.
I put something together to understand the issue at hand 🧑‍💻

For comparison I took in Scale, Duet and Carbon 
Duet, also built with stencil, has the same underlying issue, which is not really _visible_ in that sense, because the CSS selectors are scoped differently. So the Duet Checkbox looks fine, but take a look at the `checked` attribute 👀

[![Edit carbon-web-components](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7no1w)

This may be somewhat of an bigger issue if I'm not missing something 🌝

My best guess is that react processes the `checked` prop rather as an attribute than an actual prop.
@BB-19, @nowseemee could you take a closer look at that react part?

**Comment by oddcelot** [comment]
Oh btw, i did play around a bit and it seems that setting `undefined` or `null` seems to resolve into the correct attribute mapping. But i would have expected any _falsy_ value would render correctly 🤷‍♂️

**Comment by nowseemee** [comment]
It's released: `3.0.0-beta.20` - Many thanks for the quick report @BB-19 and thanks for the fix @oddcelot!
