### ISSUE TITLE
Rendering of dropdown options is broken when dropdown is part of another web component

### ISSUE THREAD

**Issue by mherwig** [telekom/scale#606]
Hello,

I tried to create a new web component that wraps `<scale-dropdown></scale-dropdown>` and has some custom logic.
When I try to set the the dropdown options via property setter the options will be rendered outside of the dropdown while the actual shadow DOM looks okay to me.

![Screenshot 2021-10-02 122227](https://user-images.githubusercontent.com/271976/135712319-31ccb8ae-4633-4d2c-b56b-5c2f1d69e356.png)

Here's a simplified version of my code that shows these issues:

index.js
```js

const template = document.createElement('template');
template.innerHTML = `<scale-dropdown label="Environment" size="small"></scale-dropdown>`;

class EnvironmentSwitch extends HTMLElement {
  constructor() {
    super(); 
    this._shadowRoot = this.attachShadow({ 'mode': 'open' });
    this._shadowRoot.appendChild(template.content.cloneNode(true));

    this._dropdown = this._shadowRoot.querySelector('scale-dropdown');
  }

  set environments(environments) {
    this._renderDropdownMenuItems(environments);
  }

  _renderDropdownMenuItems(environments) {
    const innerHTML = (environments || []).map(env => `<option value="${env.name.toLowerCase()}">${env.label}</option>`).join("\n");
    
    this._dropdown.innerHTML = innerHTML;
  }
}

window.customElements.define('eni-environment-switch', EnvironmentSwitch);
```

index.html
```html
<!doctype html>
<html>
<head lang='en'>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width'>
	<title>Environment switcher</title>
	<link rel="stylesheet" href="/node_modules/@telekom/scale-components/dist/scale-components/scale-components.css">
	<script type="module" src="/node_modules/@telekom/scale-components/dist/scale-components/scale-components.esm.js"></script>
	<script type="module" src='/dist/index.esm.js'></script>
</head>
<body>
	<eni-environment-switch></eni-environment-switch>
	<script type="module">
			let environmentSwitch = document.querySelector("eni-environment-switch");
			environmentSwitch.environments = [
					{ name: 'dev', label: 'Dev/Test', description: '', tags: ['internal'] },
					{ name: 'preprod', label: 'PreProduction', description: '', tags: ['customer'] },
					{ name: 'prod', label: 'Production', description: '', tags: ['customer'] }
			];
	</script>
</body>
</html>
```

I also tried it without bundling the code but this did not help.

I'm fairly new to web components to be honest, so please excuse me if I understood something fundamentally wrong when it comes to defining/composing new custom elements.

Best regards

Mike

**Comment by acstll** [comment]
Hey Mike, thanks for the detailed explanation and the snippets. I find it very interesting that you're trying to wrap/extend the components. (Web components are not easy to grasp, no worries :))

I was able to reproduce your case. I event got it working, unexpectedly, but after experimenting with timing, it didn't work anymore.

You did everything right, but I'm guessing you were assuming `scale-dropdown` is using the Shadow DOM, but it's not.

When components use the Shadow DOM, manipulating their light DOM children triggers an update. So doing `this._dropdown.innerHTML = innerHTML` would have worked. In our case, in the `_renderDropdownMenuItems` method you are adding some nodes to an existing light DOM tree —that's why they get rendered above the actual `select` element.

I'm pasting a modified version of your `EnvironmentSwitch` that works. I'm rendering the entire markup when the data is set. Using a `template` is good for performance, but no mandatory. I hope this helps.

```js
class EnvironmentSwitch extends HTMLElement {
  constructor() {
    super(); 
    this._shadowRoot = this.attachShadow({ 'mode': 'open' });
  }

  set environments(environments) {
    this._renderDropdownMenuItems(environments);
  }

  _renderDropdownMenuItems(environments) {
    const innerHTML = (environments || [])
      .map(env => `<option value="${env.name.toLowerCase()}">${env.label}</option>`).join("\n");
    
    // Change: render the whole thing at once
    this._shadowRoot.innerHTML = `
      <scale-dropdown label="Environment" size="small">
        ${innerHTML}
      </scale-dropdown>
    `
  }
}
```

---

We've had some issues in the past with this `scale-dropdown` component. Mainly because we use a markup-driven approach in general for the library (e.g. you need to add the `<option>` tags). Stencil allows you to "fake" the Shadow DOM rendering mechanism without it, but not without issues imho.

Your feedback got me thinking that a nice thing to do in general would be to refactor and clean up our components not using the Shadow DOM to not accept any markup, but only take data as props/attributes.
