### ISSUE TITLE
Not able to call .focus() over scale-button

### ISSUE THREAD

**Issue by lstraka-telekom** [telekom/scale#658]
When trying to call focus() over scale-btn elem it is not working : 

```
document.getElementById('test-btn').focus();  //not working
(document.getElementById('test-btn') as any).focus();  //not working
console.log(document.getElementById('test-btn')); // return correct elm so its not null ..
```
```
//template
<scale-button
      id="test-btn"
      variant="primary"
      size="small"
    >
      BTN
    </scale-button>
```
When I try it for example with tab-header element, then focus is working ...could you take a look on it ? Or I missed something and there is other speciallity how to provide focus on scale-btn ?

**Comment by acstll** [comment]
A new beta (29) release is out with the new `setFocus` method in the button and the link. Thanks again for reporting this!

**Comment by VictoriaStefanikova** [comment]
Hi.

I´m having the similar problem as reported in this issue. The difference is, that I am using toggle button instead of button. 
I have toggle group of several toggle buttons using single select option. The result I want to achieve is that whenever I click on some specific toggle button and then I click again - so the  **selected attribute** of toggle button is in the state **'false'**, I want to select the default toggle button + also move the focus.

The code below does not work on toggle button:
```
if (isSelected === 'false') {
   document.getElementById('item-default').setAttribute('selected', 'true');
   document.getElementById('item-default').shadowRoot.querySelector('toggle-button').focus();
}
```

Is there any solution to solve this problem or are you planning to include such feature for toggle button?

**Comment by mato-a** [comment]
Hi @VictoriaStefanikova,

This should work:
```
document.getElementById('item-default').setAttribute('selected', 'true');
document.getElementById('item-default').shadowRoot.querySelector('button').focus();
```

Method `setFocus()` could be added to the toggle-button (like for button and link to make it easier...)

**Comment by acstll** [comment]
> Method setFocus() could be added to the toggle-button (like for button and link to make it easier...)

totally. Will do! Re-opening this.

Thanks @mato-a and @VictoriaStefanikova.

**Comment by mato-a** [comment]
Hi @acstll, I've had some to do it, so I've made a pull request with analogical implementation to how it was implemented in button
