### ISSUE TITLE
Clicking outside the "Modal" component closes the modal

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#676]
Currently, when clicking outside the "Modal" component the modal will be closed.
We need an option to prevent this behaviour of the modal. It should stay open even if the user would click outside the modal (in order not to lose his configuration).

**Comment by acstll** [comment]
There is a `scale-before-close` event that you can use for that. You may use it like this:

```jsx
<ScaleModal onScale-before-close={event => {
  if (event.detail.trigger === 'BACKDROP') event.preventDefault()
}} />
```

(The classic camel case event name is not currently working because of [a bug](https://github.com/telekom/scale/issues/428#issuecomment-960621109), so `onScaleBeforeClose` will not work).

The event `detail` object includes a `trigger` prop with [a string value](https://github.com/telekom/scale/blob/600e2f45618f75f8f6ffa7b845ebd7ae579d9524/packages/components/src/components/modal/modal.tsx#L31) to indicate which action triggered the event, the values being:
- `CLOSE_BUTTON` - the close button on the top right corner clicked
- `ESCAPE_KEY` - escaped key pressed
- `BACKDROP` - outside of the modal clicked

I know we can better document this, we will 🙂
