### ISSUE TITLE
Activation/Deactivation of interactive components

### ISSUE THREAD

**Issue by Kaawo** [telekom/scale#779]
Greetings together,

I have noticed, that there is inconsistent usage of interactive elements. Some components (like button, accordion panel, sidebar) can be activated/deactivated by keyboard with the space and enter, others (like radio button, checkbox) only just by the space. Is this the way it was intended?

Cheers
Kay

**Comment by acstll** [comment]
Hello @Kaawo, thanks for asking!

It's probably intended and only due to how browsers handle different kind of primitive elements.

For some elements, like checkboxes or radio buttons, using Enter won't work because (this is my guess) pressing Enter in the context of a `<form>` submits the form.

In most components, it defaults to the browser behaviour (there's no extra handling), on some others, like the Flyout Menu for instance, keyboard functionality is added on top, and keys are chosen based on recommendations from the accessibility experts external team.

Is there any particular component you would expect would behave different?

**Comment by acstll** [comment]
Closing this assuming it's all good, please re-open or get in touch if not. Thanks again for your feedback.
