### ISSUE TITLE
Vite-Compatibility

### ISSUE THREAD

**Issue by DotCoyote** [telekom/scale#858]
Currently this package doesn't work with [Vite](https://vitejs.dev/), but with webpack only. Is there any plan to make it compatible?

**Comment by DotCoyote** [comment]
```sh
/app/node_modules/.vite/@telekom_scale-components_loader.js
3020|      return module[exportName];
3021|    }
3022|    return import(
   |                  ^
3023|      /* webpackInclude: /\.entry\.js$/ */
3024|      /* webpackExclude: /\.system\.entry\.js$/ */
The above dynamic import cannot be analyzed by vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.
```

**Comment by acstll** [comment]
It's a known issue. Please see https://github.com/telekom/scale/issues/369 and https://github.com/ionic-team/stencil/issues/2827

It's not directly in our hands to fix this, but we'll be glad to help.

I'm thinking you've already guessed the problem lies within Stencil's lazy loading mechanics.

A workaround (I use myself) is to load Scale via plain old script tags (either from node_modules or somewhere else) in your index.html, like this: https://github.com/telekom/scale#setup-with-plain-html — I hope this helps

**Comment by DotCoyote** [comment]
Thanks for the quick reply! Yeah, we're using that workaround for now, but of course it'd be nice to have the typescript support in the IDE 😉 

But I will watch your linked issues!

**Comment by acstll** [comment]
I agree a 100%. Better IDE support is in our roadmap 🤓  Thank you for the feedback!

**Comment by acstll** [comment]
Thank you @schrej!
