### ISSUE TITLE
escape keydown event focus issue

### ISSUE THREAD

**Issue by nikolab-pn** [telekom/scale#873]
When pressing escape anywhere on the page focus is moved to header user-menu. This is unexpected when closing modals and similar situations.

https://codesandbox.io/s/agitated-tdd-i3d6hd?file=/src/App.js
https://i3d6hd.csb.app/

Steps:
1. Open page: https://i3d6hd.csb.app/
2. Open modal
3. Click escape to close modal
4. Press enter and user-menu will open

*doesnt work from sandbox editor page needs to be opened in new window

**Comment by nowseemee** [comment]
Hi @nikolab-pn, thanks for making us aware - this is indeed not the expected behavior. We will take a look but meanwhile, you could implement your own custom behavior, programmatically focusing the button which initiated the modal to open - similar to how it was described in this issue: https://github.com/telekom/scale/issues/842
I'll come back to you when there is a proper fix, however focusing on the trigger button after closing the modal will need to be manually implemented for each use case nevertheless.

**Comment by nikolab-pn** [comment]
Hi @nowseemee, any info when this event will be fixed?

**Comment by nikolab-pn** [comment]
@marvinLaubenstein, any info when this might be fixed?
