### ISSUE TITLE
Make Card clickable also by providing onClick event handler

### ISSUE THREAD

**Issue by filipjnc** [telekom/scale#924]
Currently, a Card is only clickable if a the `url` prop is passed.

In some use-cases, this might be insufficient. For example, when using the card to open a modal. For this, you'd want to provide an `onClick` event handler, responsible for opening the modal.

The Card should have an `onClick` prop that receives a void function with the click event as param. When this prop is passed to the Card component, same styling should be applied as in the case when the `url` prop is provided. If both `url `and `onClick `are provided, `onClick `should have precedence, in order to be able to manipulate/cancel the click event before browser redirect ot new url location.

**Comment by acstll** [comment]
Thank you @filipjnc for opening this.

I'm not sure how to go about this one. Mainly because accessibility.

When the `to` prop is passed, the Card renders an `<a>` tag. And that gives you some accessibility traits for free: focus and keyboard support, plus an actual link being announced in screen readers.

You can already achieve the behaviour you're looking for, because it's possible to attach listeners for the `click` event to any element. So you could do:

```html
<scale-card to="javascript:" onclick="openModal()">Example</scale-card>
```

(You could replace `javascript:` with `#`, but then you would have to `event.preventDefault()` to avoid navigation, as you already suggested.)

Does this help?

**Comment by filipjnc** [comment]
> it's possible to attach listeners for the click event to any element

This I was unaware of, but now it seems obvious and yes, it's working and solving my issue. Thanks!
