### ISSUE TITLE
scale-toggle-button not possible to change icon color in dark mode

### ISSUE THREAD

**Issue by VictoriaStefanikova** [telekom/scale#982]
Hi. There is no possibility to change the color of icon inside scale-toggle-button component in **dark mode**. Targeting --color-primary or --color-secondary is not working. The color remains unchanged - black.

In the example below, changing background and disabled color of the button is working correctly. --color-primary is not working as expected:
```
app-toolbox-header > scale-toggle-group > scale-toggle-button::part(toggle-button) {
  --background-secondary: var(--scl-color-background-light);
  --color-primary-disabled: var(--scl-color-background-disabled);
  --color-primary: green;
}
```

Can you suggest any working solution?

**Comment by mato-a** [comment]
Hi @VictoriaStefanikova,

I should note that this bug referes to custom dark theme implemented in Scale version v3.0.0-beta.54.

This happens in v3.0.0-beta.54, due to how toggle-button is implemented: https://github.com/telekom/scale/blob/v3.0.0-beta.54/packages/components/src/components/toggle-button/toggle-button.css

In the new version (since v3.0.0-beta.100) the implementation was refactored, so that --color-primary and --color-secondary variables are actually used and should work in the new version: https://github.com/telekom/scale/blob/main/packages/components/src/components/toggle-button/toggle-button.css
