### ISSUE TITLE
Header hides the items when the header is minimised.

### ISSUE THREAD

**Issue by peterszeles** [telekom/scale#990]
When the `scale-header` minimises after scroll down on the page, the 'header__container' height stays the same as non-minimised so it can cause that any element under the minimised  header 'invisible line' is not accessible.

**Comment by acstll** [comment]
Thank you @peterszeles, for opening this!

It took me some time to understand what the problem was. But I think I know now.

The `header.header__container` element remains 128px height, so there's around 50px of content being blocked by it. In the screenshot, the first "Scroll to test header behavior" line (within those 128px) cannot be reached with the mouse, but the second does.

Can you please be so kind and confirm this is the error you're reporting?

<img width="1325" alt="Captura de pantalla 2022-04-14 a les 16 09 37" src="https://user-images.githubusercontent.com/851105/163408753-cd023f79-57a7-474f-81d9-4294d64a426f.png">

**Comment by peterszeles** [comment]
Yes, that's exactly what I reported. :)

**Comment by nowseemee** [comment]
This should be fixed in the latest published release.
